### ISSUE TITLE
Goals to be solved

### ISSUE THREAD

**Issue by WizardOfAus** [zemingyu/meetup-queue#1]
Issues at hand

- [ ] Join a meetup after start time
- [ ] Contract 1 & 2
- [ ] uPort

**Comment by WizardOfAus** [comment]
Current issue:

browser/ballot.sol:189:9: TypeError: Member "push" is not available in address[] memory outside of storage.
        _meetup.registrationList.push(msg.sender);
        ^---------------------------^
function joinNextMeetup (bytes32 _userName)
        public        
        // returns (bool)
    {
        require(users[_userName] == msg.sender);
        require(users[_userName] != address(0));        

        uint256 _meetupId = meetups.length -1;
        Meetup memory _meetup = meetups[_meetupId];

        // Can't join a meetup that has already started.
        require(now < _meetup.startTime);        

        // Can't join twice
        for (uint i = 0; i < _meetup.registrationList.length; i++) {
            if (_meetup.registrationList[i] == msg.sender) {
                revert();
            }
        }      

        _meetup.registrationList.push(msg.sender);//THIS IS THE LINE WITH THE ERROR

    }

**Comment by zemingyu** [comment]
After making _meetup a storage variable, this is resolved.
`        Meetup storage _meetup = meetups[_meetupId];`
